# Generated by Django 4.2.3 on 2023-07-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.CharField(max_length=30)),
                ('card_number', models.CharField(max_length=7)),
                ('cvv', models.FloatField(max_length='3')),
                ('price', models.FloatField()),
                ('card_balance', models.FloatField()),
                ('duration', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
