# Generated by Django 4.2.4 on 2023-08-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='card_dif',
            field=models.CharField(choices=[('Debit Card', 'Debit'), ('Credit Card', 'Credit')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='cards',
            name='card_limit',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
