# Generated by Django 4.2.3 on 2023-07-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcards', '0002_alter_cards_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='card_type',
            field=models.CharField(blank=True, choices=[('Visa', 'Visa'), ('Master', 'Master')], max_length=8),
        ),
    ]
