# Generated by Django 4.2.3 on 2023-07-07 00:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('maxcards', '0003_cards_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='card_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
