# Generated by Django 4.2.3 on 2023-07-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcards', '0006_alter_cards_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_type',
            field=models.CharField(choices=[('Visa C', 'Visa Card'), ('Master C', 'Master Card')], max_length=8),
        ),
    ]
