# Generated by Django 4.2.3 on 2023-07-07 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maxcards', '0008_alter_cards_card_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cards',
            options={'verbose_name_plural': 'Card'},
        ),
        migrations.CreateModel(
            name='Payment_screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='Screenshots')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payment_screenshot',
            },
        ),
    ]
