# Generated by Django 4.2.3 on 2023-07-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcards', '0009_alter_cards_options_payment_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_screenshot',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
