# Generated by Django 4.2.3 on 2023-07-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcards', '0010_alter_payment_screenshot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_screenshot',
            name='transaction_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
