# Generated by Django 4.2.3 on 2023-07-07 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maxcards', '0011_payment_screenshot_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='card_status',
        ),
        migrations.CreateModel(
            name='User_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Approved', 'Approved')], default='Pending', max_length=8, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxcards.cards')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
