# Generated by Django 4.2.3 on 2023-07-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcards', '0012_remove_cards_card_status_user_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='transaction_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
