# Generated by Django 4.2.3 on 2023-07-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcards', '0013_cards_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='user_orders',
            name='transaction_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
