# Generated by Django 4.2.3 on 2023-07-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcards', '0015_user_orders_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_orders',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
