# Generated by Django 4.2.3 on 2023-07-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxcards', '0016_alter_user_orders_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_orders',
            name='order_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user_orders',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
