# Generated by Django 4.2.3 on 2023-07-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxcards', '0017_user_orders_order_id_alter_user_orders_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_orders',
            name='order_id',
        ),
    ]
